# Generated by Django 5.2 on 2025-04-09 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reg', models.DateField(db_index=True, help_text='Format: YYYY-MM-DD')),
                ('type', models.CharField(db_index=True, max_length=20)),
                ('maker', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(db_index=True, max_length=50)),
                ('colour', models.CharField(max_length=20)),
                ('fuel', models.CharField(db_index=True, max_length=20)),
                ('state', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-date_reg'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Format: YYYY-MM-DD', unique=True)),
                ('ron95', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('ron97', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('diesel', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('diesel_eastmsia', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
            ],
            options={
                'db_table': 'fuel_prices',
                'ordering': ['-date'],
            },
        ),
    ]
