# Generated by Django 5.2 on 2025-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelprice',
            old_name='diesel_eastmsia',
            new_name='diesel_eastern',
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(db_index=True, help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AlterUniqueTogether(
            name='fuelprice',
            unique_together={('date',)},
        ),
    ]
