# Generated by Django 5.1.7 on 2025-04-18 17:02
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_diesel_eastmsia_fuelprice_diesel_eastern_and_more'),
    ]

    operations = [migrations.CreateModel(
    name='CPIData',
    fields=[
        ('id', models.AutoField(primary_key=True, serialize=False)),
        ('date', models.CharField(max_length=7, db_index=True, help_text='Format: YYYY-MM')),
        ('state', models.CharField(max_length=100, db_index=True)),
        ('division', models.CharField(max_length=100, db_index=True)),
        ('index', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
    ],
    options={
        'db_table': 'cpi_data',
        'ordering': ['-date'],
        'unique_together': {('date', 'state', 'division')},
        'verbose_name': 'CPI Data',
        'verbose_name_plural': 'CPI Data',
    },
),
    ]
