# Generated by Django 5.1.7 on 2025-05-08 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250419_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPIRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True, help_text='Format: YYYY-MM-DD')),
                ('division', models.IntegerField(db_index=True)),
                ('desc_en', models.CharField(db_index=True, max_length=100)),
                ('index', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'ipi_data',
                'ordering': ['-date'],
                'unique_together': {('date', 'division')},
            },
        ),
    ]
