# Generated by Django 5.1.7 on 2025-05-08 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ipirecord_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipirecord',
            table='ipi_data',
        ),
        migrations.CreateModel(
            name='IPINationalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True, help_text='Format: YYYY-MM-DD')),
                ('desc_en', models.TextField()),
                ('index', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'IPI National Record',
                'verbose_name_plural': 'IPI National Records',
                'db_table': 'ipi_national_data',
                'ordering': ['-date'],
                'unique_together': {('series', 'date')},
            },
        ),
    ]
