# Generated by Django 5.1.7 on 2025-05-08 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ipirecord_table_ipinationalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPI1DRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True, help_text='Format: YYYY-MM-DD')),
                ('index', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('index_sa', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seasonally Adjusted Index')),
            ],
            options={
                'db_table': 'ipi_Data_1d',
                'ordering': ['-date'],
                'unique_together': {('series', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='IPINationalRecord',
        ),
        migrations.AlterModelTable(
            name='ipirecord',
            table='ipi_data_2d',
        ),
    ]
