# Generated by Django 5.1.7 on 2025-05-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ipi1drecord_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipi1drecord',
            table='ipi_Data_1d',
        ),
        migrations.AlterModelTable(
            name='ipirecord',
            table='ipi_Data_2d',
        ),
    ]
