# Generated by Django 5.1.7 on 2025-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ipi1drecord_table_alter_ipirecord_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipirecord',
            name='series',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
