# Generated by Django 5.1.7 on 2025-05-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_ipirecord_series'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipirecord',
            unique_together={('date', 'division', 'series')},
        ),
    ]
